version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: proxy_spike
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./spike:/etc/nginx/sites-enabled/spike
      - ./server.crt:/etc/nginx/ssl/server.crt
      - ./server.key:/etc/nginx/ssl/server.key
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8443:8443
